import {
  Atom,
  Braces,
  Boxes,
  BrainCircuit,
  Cloud,
  Code2,
  CodeXml,
  Database,
  FileCode2,
  GitBranch,
  Image,
  KeyRound,
  Layers3,
  Network,
  Package,
  PanelsTopLeft,
  Palette,
  Send,
  Server,
  ShieldCheck,
  Sparkles,
  Video,
  Workflow,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

const technologies = {
  "HTML5": [CodeXml, "var(--pink)"],
  "CSS3": [Palette, "var(--cyan)"],
  "JavaScript (ES6+)": [FileCode2, "var(--amber)"],
  "React.js": [Atom, "var(--cyan)"],
  "Redux Toolkit": [Layers3, "var(--violet)"],
  "Tailwind CSS": [Wind, "var(--cyan)"],
  "Node.js": [Server, "var(--lime)"],
  "Express.js": [Code2, "var(--text)"],
  "JWT": [KeyRound, "var(--amber)"],
  "MongoDB": [Database, "var(--lime)"],
  "Google Gemini API": [Sparkles, "var(--violet)"],
  "Unsplash API": [Image, "var(--pink)"],
  "Pexels API": [Image, "var(--cyan)"],
  "Tenor API": [Video, "var(--amber)"],
  "Git": [GitBranch, "var(--pink)"],
  "GitHub": [Code2, "var(--text)"],
  "Vite": [Zap, "var(--violet)"],
  "Postman": [Send, "var(--pink)"],
  "npm": [Package, "var(--lime)"],
  "VS Code": [Code2, "var(--cyan)"],
  "RESTful APIs": [Network, "var(--cyan)"],
  "Responsive Web Design": [PanelsTopLeft, "var(--pink)"],
  "DOM Manipulation": [Braces, "var(--amber)"],
  "State Management (Redux Toolkit)": [Workflow, "var(--violet)"],
  "MVC Architecture": [Boxes, "var(--lime)"],
  "Auth & Security": [ShieldCheck, "var(--amber)"],
  "Cloud": [Cloud, "var(--cyan)"],
  "Tools & Utilities": [Wrench, "var(--amber)"],
  "AI & Third-Party APIs": [BrainCircuit, "var(--violet)"],
};

export function getTechnology(label) {
  const [Icon, accent] = technologies[label] || [Code2, "var(--cyan)"];
  return { Icon, accent };
}